### ISSUE TITLE
Missing tag, missing release and other issues

### ISSUE THREAD

**Issue by sashkab** [AquaQAnalytics/grafana-kdb-datasource-ws#27]
Hi,

Looking at [kdb+ plugin on grafana.com](https://grafana.com/grafana/plugins/aquaqanalytics-kdbadaptor-datasource/) it shows that version 1.0.2 is the latest version. 

<img width="359" alt="screenshot_2021 06 24_150106" src="https://user-images.githubusercontent.com/868842/123318429-2fe0ad00-d4fd-11eb-86fe-b3f2139d83a0.png">

In Github repository, latest release is v2.0.0. 

<img width="914" alt="screenshot_2021 06 24_150245" src="https://user-images.githubusercontent.com/868842/123318493-438c1380-d4fd-11eb-8f9f-1d601cc9b9cd.png">

Would be nice if you could:

1. create tag which will point to the code which is available as v1.0.2 on grafana.com
2. release v2.0.0 to grafana.com
3. provide update to see why neither of two versions work with Grafana v8 (query screen is empty)

Thanks!

**Comment by frenzy21** [comment]
We are working on updating to Support the Grafana 8.0 release. A few changes have caused issues.

Expecting a release before end of September.

**Comment by sashkab** [comment]
@frenzy21 thanks for answering third question, what about first two? Can they be addressed?

**Comment by sashkab** [comment]
@frenzy21 Any updates on this? It's December already... 

Update: looks like 3.0.0 was released, but wasn't published on grafana.com.

**Comment by sashkab** [comment]
Looks like 3.0.0 was published on grafana.com, closing this issue. 
Thanks!
